name: CI/CD Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest nose coverage  # Added nose and coverage

      # Node.js setup (conditional)
      - name: Check for Node project
        id: check-node
        run: |
          if [ -f package.json ]; then
            echo "node_project=true" >> $GITHUB_OUTPUT
          else
            echo "node_project=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check-node.outputs.node_project == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        if: steps.check-node.outputs.node_project == 'true'
        run: npm install

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      # Added Nose test step as specified in Exercise 3
      - name: Run unit tests with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      # Kept existing pytest for compatibility
      - name: Run Python tests with pytest
        run: |
          python -m pytest tests/
          echo "Python tests completed"

      # Node.js tests (conditional)
      - name: Run Node tests
        if: steps.check-node.outputs.node_project == 'true'
        run: |
          npm test
          echo "Node tests completed"

      - name: Build project
        if: steps.check-node.outputs.node_project == 'true'
        run: npm run build

      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to staging..."
          # Add deployment commands here
